import Head from "next/head";
import Image from "next/image";
import Header from "components/Header";
import ToolBox from "components/ToolBox";
import Footer from "components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
<div>
      <h2 className="p-3 md:p-8 lg-p-14 pt-12 md:pt-16 lg:pt-18 text-2xl md:text-4xl lg:text-5xl  font-bold  text-slate-700 text-center">
        Get
        <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-500 to-pink-600">
          {" "}
          Link-Preview{" "}
        </span>
        of any url <br /> and all
        <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-500 to-pink-600">
          {" "}
          Metadata{" "}
        </span>
        <br />
        at one click
      </h2>
      <ToolBox />
      </div>
      <Footer />
    </>
  );
}
